### ISSUE TITLE
Fout bagextract.py : GDAL Python bindings zijn niet beschikbaar (Ubuntu)

### ISSUE THREAD

**Issue by EduardWitteveen** [opengeogroep/NLExtract#112]
Bij het uitvoeren van het commando bagextract.py krijg ik de foutmelding: FATAAL: GDAL Python bindings zijn niet beschikbaar, installeer bijv met 'apt-get install python-gdal'

# Foutmelding:
```bash
eduard@eduard-server:/data$ python /data/bagextract/src/bagextract.py  -c -v
DEBUG: Configuratiebestand is /data/opengeogroep-NLExtract-820f05d/bag/extract.conf
Waarschuwing! met dit commando worden database tabellen opnieuw aangemaakt. Doorgaan? ([N]/j): j
INFO: Start 2014-01-20 12:07:42
INFO: alle database tabellen weggooien en opnieuw aanmaken...
INFO: Probeer te verbinden...
DEBUG: verbonden met de database 'bagextractdb', schema 'public', connId=3
INFO: database script uitvoeren...
DEBUG: database commit ok connId=3
DEBUG: database connectie 3 gesloten
INFO: script is uitgevoerd
INFO: Initieele data (bijv. gemeenten/provincies) inlezen...
running with lxml.etree
FATAAL: GDAL Python bindings zijn niet beschikbaar, installeer bijv met 'apt-get install python-gdal'
```

# Installatie script
## Python : 
```bash
	~$ sudo apt-get install python-setuptools python-dev libpq-dev libxml2 gdal-bin python-gdal python-psycopg2
```
## Postgis: 
```bash
	~$ sudo apt-get install postgresql-9.1-postgis
	~$ sudo -u postgres createuser --createdb --login --superuser `whoami` 
	~$ createdb postgis
	~$ createlang plpgsql postgis
	~$ psql -d postgis -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql
	~$ psql -d postgis -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql

	~$ createuser -D -R -S -P bagextract
	   password: Welkom01
	~$ createdb --encoding=UNICODE --template postgis --owner=bagextract bagextractdb
	~$ psql -d bagextractdb -c "ALTER TABLE geometry_columns OWNER TO bagextract;"
	~$ psql -d bagextractdb -c "GRANT ALL ON DATABASE bagextractdb TO bagextract;"

	~$ sudo vi/etc/postgresql/9.1/main/postgresql.conf
```
( wanneer vi te moeilijk is:  sudo apt-get install mped; sudo mped /etc/postgresql/9.1/main/postgresql.conf )
		Zoek naar de volgende regel:
```asciidoc
			#listen_addresses = 'localhost'
```
En voeg hierboven de volgende regel toe:		
```asciidoc
			listen_addresses = '*' 
```
```bash
	~$ sudo vi /etc/postgresql/9.1/main/pg_hba.conf
```
( wanneer vi te moeilijk is:  sudo apt-get install mped; sudo mped /etc/postgresql/9.1/main/pg_hba.conf )
Ga helemaal naar het einde van het bestand en voeg de volgende regel toe:
```asciidoc
			host all all 192.168.1.0/24 md5
```
(hierbij gaan we ervanuit dat 192.168.1.0 het eigen interne ip adres is)
```bash
	~$ sudo /etc/init.d/postgresql restart
```

## Scripts:
```bash
	~$ cd  /data
	~$ wget -O NLExtract.zip  https://github.com/opengeogroep/NLExtract/zipball/master
	~$ unzip NLExtract.zip
	~$ ln -s opengeogroep-NLExtract-820f05d/bag/ ./bagextract
	~$ vi /data/bagextract/extract.conf
```
```asciidoc
		[DEFAULT]
		database 	= bagextractdb
		schema 		= public
		host     	= localhost
		user     	= bagextract
		password 	= Welkom01
		port 		= 5432
```
## Structuur maken met script:
```bash
	~$ export GDAL_DATA=/usr/share/gdal/1.9
	~$ python /data/bagextract/src/bagextract.py  -c -v
```
<<< fout!!! >>>>

# Sources.list
```asciidoc
# deb cdrom:[Ubuntu 12.04 LTS _Precise Pangolin_ - Release i386 (20120423)]/ precise main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://nl.archive.ubuntu.com/ubuntu/ saucy main restricted
deb-src http://nl.archive.ubuntu.com/ubuntu/ saucy main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://nl.archive.ubuntu.com/ubuntu/ saucy-updates main restricted
deb-src http://nl.archive.ubuntu.com/ubuntu/ saucy-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://nl.archive.ubuntu.com/ubuntu/ saucy universe
deb-src http://nl.archive.ubuntu.com/ubuntu/ saucy universe
deb http://nl.archive.ubuntu.com/ubuntu/ saucy-updates universe
deb-src http://nl.archive.ubuntu.com/ubuntu/ saucy-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://nl.archive.ubuntu.com/ubuntu/ saucy multiverse
deb-src http://nl.archive.ubuntu.com/ubuntu/ saucy multiverse
deb http://nl.archive.ubuntu.com/ubuntu/ saucy-updates multiverse
deb-src http://nl.archive.ubuntu.com/ubuntu/ saucy-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://nl.archive.ubuntu.com/ubuntu/ saucy-backports main restricted universe multiverse
deb-src http://nl.archive.ubuntu.com/ubuntu/ saucy-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu saucy-security main restricted
deb-src http://security.ubuntu.com/ubuntu saucy-security main restricted
deb http://security.ubuntu.com/ubuntu saucy-security universe
deb-src http://security.ubuntu.com/ubuntu saucy-security universe
deb http://security.ubuntu.com/ubuntu saucy-security multiverse
deb-src http://security.ubuntu.com/ubuntu saucy-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu precise partner
# deb-src http://archive.canonical.com/ubuntu precise partner

## This software is not part of Ubuntu, but is offered by third-party
## developers who want to ship their latest software.
deb http://extras.ubuntu.com/ubuntu saucy main
deb-src http://extras.ubuntu.com/ubuntu saucy main
```

**Comment by justb4** [comment]
Als NLExtract-BAG ergens goed installeert is het Ubuntu. Al zovele malen gedaan. Ik denk dat hier toch een unieke situatie is (ontstaan). Graag toch sluiten, hopelijk ook inmiddels opgelost.

**Comment by EduardWitteveen** [comment]
Hallo Just,

Dit was een schone install van ubuntu en ook in een nieuwe virtuele machine liep ik hier tegenaan. Ik ben bereid om het opnieuw te testen, maar het zomaar sluiten vind ik persoonlijk iets te kort door de bocht. Ik wacht hier nog steeds op omdat ik de gemeentelijke gegevens wil vergelijken met de gegevens bij het kadaster.

Graag je reactie,

Groeten,

Eduard

**Comment by justb4** [comment]
Ok blijkbaar nog niet opgelost. Wat nog zou kunnen is om package ` libgdal-dev` (https://launchpad.net/ubuntu/saucy/i386/libgdal-dev/1.9.0-3.1ubuntu4) te installeren, dus totaal:

         apt-get install libgdal-dev
         apt-get install python-gdal

En dan mogelijk een `ldconfig` doen. Ik zie bij mij installed:

         apt-show-versions |grep gdal
        libgdal-dev:amd64/saucy 1.10.1+dfsg-2~saucy1 uptodate
        libgdal1-dev:all/saucy 1.10.1+dfsg-2~saucy1 uptodate
        libgdal1h:amd64/saucy 1.10.1+dfsg-2~saucy1 uptodate
        python-gdal:amd64/saucy 1.10.1+dfsg-2~saucy1 uptodate

**Comment by EduardWitteveen** [comment]
Hallo Just,

Ik heb nu de handleiding gevolgd van
http://docs.nlextract.nl/en/latest/bagextract.html, maar helaas loop ik
hier weer vast:

Ubuntu desktop installeren op een virtuele machine van 20 GB
> http://releases.ubuntu.com/14.10/ubuntu-14.10-desktop-amd64.iso.torrent
> servername: geoserver
> username: geoserver
> password: geoserver

*# in ubuntu hebben toch sudo nodig?*

sudo apt-get update
> sudo apt-get upgrade
> sudo apt-get install python-software-properties
> sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
> sudo apt-get update
> sudo apt-get install postgis postgresql-9.1 postgresql-contrib
> E: Package 'postgresql-9.1' has no installation candidate
> *# welke versie kan er worden gebruikt?*
> sudo apt-get install postgis postgresql postgresql-contrib
> *# waarom is de volgende regel nodig? pgadmin?*
> sudo -u postgres psql -c "CREATE EXTENSION adminpack;"
> psql -h localhost -U postgres template1
> *# welk wachtwoord? (moet ik deze aanpassen?)*


Ik heb er geen probleem mee om er tijd in te steken om het werkend te
krijgen, kun je me aangeven welke distributie en versie van debian jij
gebruikt?

Groeten,

Eduard

**Comment by justb4** [comment]
Is dit opgelost. Ik ga er even van uit, anders weer heropenen.

**Comment by jeroenvermunt** [comment]
Ik liep hier weer tegenaan op Ubuntu 20.04 met GDAL 3.4.1. Ik kreeg het maar niet werkend met sudo-apt get en pip3 install. Uiteindelijk heb ik een pre-build wheel gevonden voor gdal 3.4.1 en dit direct geinstalled als volgt:
`python3 -m pip install https://sourceforge.net/projects/gdal-wheels-for-linux/files/GDAL-3.4.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl`

**Comment by justb4** [comment]
@jeroenvermunt dit was wel een heel oud issue voor BAG versie 1. Voor BAG v2 (sinds 2021) is idd recente GDAL nodig.
