### ISSUE TITLE
Dutch meegeven aan ts_vector bij textsearchable_adres

### ISSUE THREAD

**Issue by milovanderlinden** [opengeogroep/NLExtract#117]
Voorbeeld:

In de huidige configuratie worden adressen op de laan van Oceanië niet gevonden wanneer een gebruiker de ë heeft vervangen door een e
```sql
SELECT to_tsvector('laan van oceanië') , 
    to_tsvector('laan van oceanië') 
    @@ to_tsquery('laan&van&oceanie');
```
resulteert in:
```
to_tsvector                     |   ?column?
-----------------------------------------
"'laan':1 'oceanië':3 'van':2"  |  f
```
De f betekent "false"; geen match gevonden.

De oplossing:

```sql
SELECT to_tsvector('dutch', 'laan van oceanië'), 
   to_tsvector('dutch', 'laan van oceanië') 
   @@ to_tsquery('dutch','laan&van&oceanie');
```

resulteert in:

```
to_tsvector              |   ?column?
-----------------------------------------
"'lan':1 'oceanie':3"    |   t
```
En dat is correct! Het enige is dat je bij de constructie van de ts_query niet moet vergeten om _dutch_ mee te geven als taal

**Comment by justb4** [comment]
Hier is geen sprake van echt issue of PR, dus ik sluit.
