### ISSUE TITLE
Top10NL/style/sld algemeen: wegdeel_hartlijn straatnaam verkeerd

### ISSUE THREAD

**Issue by mtoonen** [opengeogroep/NLExtract#124]
Het label voor straatnamen is verkeerd voor de tabelmapping: er bestaat ofwel straatnaamnl of straatnaamfries.
Is dit bewust gedaan zodat je als gebruiker een keus moet maken?

**Comment by justb4** [comment]
Opgelost dus sluiten, bedankt Meine.
