### ISSUE TITLE
bagextract verwijdert data uit schema "public"

### ISSUE THREAD

**Issue by raymondnijssen** [opengeogroep/NLExtract#131]
Zojuist heb ik een nieuwe levering ingelezen in een nieuw schema (bag201409). Ik had al een eerdere levering in het schema "public" staan.  In extract.conf heb ik het schema aangepast:

database = bag
schema   = bag201409
host     = 192.168.1.203

De nieuwe data is keurig in het nieuwe schema beland, maar in het schema public zijn alle bag-tabellen verwijderd. :( Dat was zeker niet mijn bedoeling en het lijkt me een bug. Zo niet dan is een dikke waarschuwing erg wenselijk.

Ook loop ik nu vast omdat  ik geen adressentabel kan genereren met adres-tabel.sql omdat hier geen schemanamen in worden gebruikt.

**Comment by justb4** [comment]
@raymondnijssen ik zie nog steeds niet echt een probleem wat betreft weggooien uit `public` zolang je specifieke schema-namen gebruikt. Wat wel belangrijk is, en daarom staan er geen schema-namen in de DB scripts is dat je `bag-extract.sh` (met -q optie) deze SQL scripts laat uitvoeren. Alleen dan garandeer je dat het specifieke schema uit je config file wordt gebruikt. Dus bijv `./bag-extract.sh -q adres-tabel.sql` anders wordt natuurlijk `public` gebruikt.

Dan wil ik deze issue graag sluiten tenzij je echt deze fout in een reproduceerbaar scenario kunt geven..
