### ISSUE TITLE
ERROR: fout nsmap in XML DOM processing

### ISSUE THREAD

**Issue by skinkie** [opengeogroep/NLExtract#139]
Ik zie bovenstaande erg vaak voorkomen. Herkennen we dat?

**Comment by skinkie** [comment]
Het lijkt in ieder geval dat de code niet werkt zonder lxml.

**Comment by justb4** [comment]
Ja klinkt bekend, helaas, is duplicate van issue #72 . Deze kan dus gesloten. Het stukje fallback code zit in etree.py (ooit door jou authored?). Maar kan zijn dat er desondanks lxml-specifieke API-calls zijn.
