### ISSUE TITLE
mutatiebestand importeren lukt niet omdat 'extract_datum' niet in nlx_bag_info staat

### ISSUE THREAD

**Issue by hpfast** [opengeogroep/NLExtract#140]
Als ik een mutatiebestand probeer te importeren, krijg ik de volgende melding:

    $ ~/bin/NLExtract/bag/bin/bag-extract.sh -f ./extract.conf -e ~/bag-mutaties/9999MUT22022015-23022015.zip 
    running with lxml.etree
    INFO: Start 2015-03-12 12:56:45
    INFO: process: verwerk /home/me/bag-mutaties/9999MUT22022015-23022015.zip
    INFO: mutatiebestand 9999MUT22022015-23022015.zip is van eerdere datum-range dan BAG ==> overslaan
    INFO: End 2015-03-12 12:56:45

Volgens mij hoeft dit niet te breken. Als ik de check in bagfilereader.py die hiervoor zorgt in commentaar zet (regels 89-93), dan gaat de import goed. De record met sleutel 'extract_datum' ontbreekt gewoon in mijn `nlx_bag_info` tabel. Ik kan niet vinden waar dit in `nlx_bag_info` gezet zou worden.

Moet die er wel in komen te staan, of zou deze check op een andere manier moeten gebeuren?

**Comment by justb4** [comment]
Bij het inlezen van de volledige BAG worden verschillende meta-data gegevens uitgelezen, met name uit het bestand ``Leveringsdocument-BAG-Extract.xml``, en geplaatst in de tabel ``nlx_bag_info``. O.a. het veld ``extract_datum`` met de stand-datum van de BAG levering. Bijv met waarde ``20141231`` (YYYYMMDD).  Bij het inlezen van mutatie-bestanden wordt dit veld geraadpleegd om te waarborgen dat alleen mutaties van na de stand-datum worden verwerkt. Daarnaast wordt gechecked of een mutatie-bestand al ingelezen is via de tabel ``nlx-bag-log``. 

Ik kan niet nagaan hoe je de BAG ingelezen hebt, of bijv alleen een deel. Ipv van code te wijzigen zou je ook handmatig het veld ``extract_datum`` kunnen aanpassen maar beter is om de file ``Leveringsdocument-BAG-Extract.xml`` in je verwerking mee te nemen. 

Het achterliggende  idee is dat we een directory hebben waar automatisch mutatie-bestanden worden verzameld en steeds NLExtract wordt gedraaid. Door de twee boven beschreven mechanismen (datum veld en bijhouden ingelezen bestanden) houden we de ingelezen data consistent.

**Comment by hpfast** [comment]
ok, duidelijk, en een goed mechanisme lijkt me!

ik heb de BAG van mirror.openstreetmap.nl/bag/maandcyclus gebruikt. Daar staat geen `Leveringsdocument-BAG-Extract.xml` bij, wel bij oudere BAG downloads van nationalegeoregister.nl, dus dat zal het wel zijn.

Ik had openstreetmap.nl gebruikt omdat nationaalgeoregister.nl in maanden geen update had gehad. Maar dagelijkse mutatiebestanden zouden dat juist van minder belang maken, want dan kan je up-to-date blijven ongeacht hoe lang geleden de startdatum (volledige import) is geweest.

bedankt.
