### ISSUE TITLE
Windows regeleinden zorgen voor ^M weergave bij git diff

### ISSUE THREAD

**Issue by milovanderlinden** [opengeogroep/NLExtract#145]
Op zich geen probleem, maar als er ontwikkelaars meedoen vanaf linux werkstations met een IDE, dan loop je het risico dat de ^M wordt vervangen bij een "save" en dat deze onterecht als diff worden gezien.

Wat is wijsheid, alle regeleinden omzetten naar linux of mixed regeleinden gewoon accepteren?

**Comment by mprins** [comment]
eenmalig alle regeleinden omzetten/harmoniseren en dan een `.gitattributes` gebruiken om de gekozen conventie te forceren.
zie: https://help.github.com/articles/dealing-with-line-endings/

**Comment by justb4** [comment]
Is dit nog relevant? Anders sluiten.
