### ISSUE TITLE
Dubbelingen door koppeling van pand, verblijfsobject en gebruikersdoel

### ISSUE THREAD

**Issue by danieltulp** [opengeogroep/NLExtract#146]
Door het koppelen van panden, verblijfsonjecten en gebruikersdoel ontstaan er dubbelingen. In een e-mail wisselinge met Just daarover gehad, dit was zijn antwoord voor de records:

> Ik ben het nagegaan op de BAG Amstelveen. Ik krijg idd meerdere records per adres/VBO. Bijv voor Amsterdamseweg Amstelveen (veel Panden/VBO's met meerdere gebruiksdoelen) deze record-aantallen in de resultaat-tabel:

> 553 (zonder Pand en VBO gebrdoel koppeling)
> 598 (met Pand en VBO gebrdoel koppeling)
> 574 (met Pand en zonder VBO gebrdoel koppeling)

> Zie dubbelingen waar bijv bouwjaren verschillen (nr 108). Denk dat de grond van het probleem is dat de JOIN gedaan wordt op de VIEWs verblijfsobjectpandactueel en verblijfsobjectgebruiksdoelactueel.
Daar zitten hoogstwaarschijnlijk de dubbelingen op status in. Er zouden VIEWs verblijfsobjectpandactueelbestaand en verblijfsobjectgebruiksdoelactueelbestaand moeten zijn om dit op te lossen. Dat is weer lastig omdat de status niet in de onderliggende tabellen zit. Dit zijn tabellen om multipliciteit en N-M koppeling op te lossen.

> Dit is meer een NLExtract issue. Weet niet een snelle oplossing, althans niet in korte tijd maar is wel op te lossen. Kun je in ieder geval dit als een NLExtract issue invoeren en op mailing lijst zetten? Je bent de eerste die deze koppelingen maakt, althans waar ik over hoor.

DIt is de SQL query waarmee ik een niet genormaliseerde tabel heb gemaakt van de NLextract PostGis database:

    CREATE TABLE bagwe.bagnlextract_nietnormtabel AS 
     SELECT o.openbareruimtenaam AS straatnaam,
        n.huisnummer,
        n.huisletter,
        n.huisnummertoevoeging,
        n.postcode,
            CASE
                WHEN wp2.woonplaatsnaam IS NULL THEN w.woonplaatsnaam
                ELSE wp2.woonplaatsnaam
            END AS woonplaats,
            CASE
                WHEN p2.gemeentenaam IS NULL THEN p.gemeentenaam
                ELSE p2.gemeentenaam
            END AS gemeente,
            CASE
                WHEN p2.provincienaam IS NULL THEN p.provincienaam
                ELSE p2.provincienaam
            END AS provincie,
        v.oppervlakteverblijfsobject AS oppervlakte,
        vg.gebruiksdoelverblijfsobject AS gebruiksfunctie,
        pand.bouwjaar,
        v.geopunt,
        pand.geovlak,
        v.identificatie AS verblijfsobjectid,
        n.identificatie AS nummeraanduidingid,
        pand.identificatie AS pandid
       FROM bagnlextract.verblijfsobjectactueelbestaand v
         JOIN bagnlextract.nummeraanduidingactueelbestaand n ON n.identificatie = v.hoofdadres
         JOIN bagnlextract.openbareruimteactueelbestaand o ON n.gerelateerdeopenbareruimte = o.identificatie
         JOIN bagnlextract.woonplaatsactueelbestaand w ON o.gerelateerdewoonplaats = w.identificatie
         JOIN bagnlextract.gemeente_woonplaatsactueelbestaand g ON g.woonplaatscode = w.identificatie
         JOIN bagnlextract.gemeente_provincie p ON g.gemeentecode = p.gemeentecode
         JOIN bagnlextract.verblijfsobjectpandactueel vp ON v.identificatie = vp.identificatie
         JOIN bagnlextract.pandactueelbestaand pand ON vp.gerelateerdpand = pand.identificatie
         JOIN bagnlextract.verblijfsobjectgebruiksdoelactueel vg ON v.identificatie = vg.identificatie
         LEFT JOIN bagnlextract.woonplaatsactueelbestaand wp2 ON n.gerelateerdewoonplaats = wp2.identificatie
         LEFT JOIN bagnlextract.gemeente_woonplaatsactueelbestaand g2 ON g2.woonplaatscode = wp2.identificatie
         LEFT JOIN bagnlextract.gemeente_provincie p2 ON g2.gemeentecode = p2.gemeentecode
      ORDER BY n.postcode;

**Comment by justb4** [comment]
> 
> Ik heb een platgeslagen (niet genormaliseerde) tabel (zie github issue 
> voor SQL).
> 
> Hierin staan meerdere adressen (combinatie postcode, huisnummer en 
> toevoegingen) die meer dan 1 keer voorkomen met dezelfde verblijfsobject 
> identificatie (in mijn tabel verblijfsobjectid), met verschillende 
> verblijfsfuncties en dezelfde oppervlakte voor alle records met dezelfde 
> verblijfsobject identificatie. Het gekke is dat de pand identificatie 
> dan vervolgens weer kan verschillen.
Dit laatste zou weer kunnen omdat in zeldzame gevallen een VBO aan meerdere Panden gekoppeld is en/of omdat er bij wijzigen PND status een ander Pand gekoppeld is. 

De crux voor het oplossen van issue #146 zit erin dat de actueelBESTAANDE VIEWs (ipv nu alleen -actueel) moeten worden gegenereerd in NLExtract-BAG voor de tussentabel VBO-PND en VBO-gebruiksdoel.

**Comment by bartkraan** [comment]
Beste Daniël,

Het beschreven effect van deze join in je gedenormaliseerde tabel is precies wat verwacht moet worden. Het is conform het datamodel van de BAG.
In de BAG kan een verblijfsobject in één of meerdere panden zitten en een verblijfsobject heeft één of meerdere gebruiksdoelen.
Als je dan gaat joinen tot een gedenormaliseerde tabel krijg je een tabel met meerdere records per verblijfsobject. Het gebruik van de actueelbestaand views helpt dan niet om er weer één record per VBO van te maken.
Indien je een gedenormaliseerde tabel wilt met slechts één record per verblijfsobject, dan zul je op VBOid moeten groeperen.

Groet,
Bart Kraan

**Comment by danieltulp** [comment]
Bart,

dank voor je reactie, wellicht naar aanleiding van de bijeenkomst van
afgelopen zaterdag.

Dus als ik het goed begrijp is het vanuit de BAG niet mogelijk om een
oppervlakte te krijgen per gebruiksdoel van een verblijfsobject, maar
alleen van alle gebruiksdoelen van een verblijfsobject samen. Dat is jammer.

Ik zie nu inderdaad in dat de oppervlakte voor het verblijfsobject is
gespecificeerd en niet voor de gebruiksfunctie.

Groeten,
Daniël Tulp

Groeten,
Daniël

Op 6 juli 2015 10:25 schreef bartkraan <notifications@github.com>:

**Comment by justb4** [comment]
Zie dus pull request #148 en mijn commentaar. Maar idd  oppervlakte blijft voor het verblijfsobject als geheel, en niet per gebruiksfunctie.

**Comment by justb4** [comment]
Dit issue en PR #148 staan nog steeds open. Met het oog op komende versie NLExtract wil ik graag tot een cleane oplossing komen, uit mijn hoofd deze volgorde: 

1. `status` en `geom_valid` aan alle multiattr tabellen `verblijfsobjectgebruiksdoel`, `verblijfsobjectpand` en `adresseerbaarobjectnevenadres` toevoegen (Python code).

2.  nieuwe VIEWs die huidig stramien `*actueel` naar `*actueelbestaand` volgen

Ad 1) kan in dit issue aparte PR gedaan worden. Ad 2) bestaande PR #148 (VIEWs) SQL aanpassen

**Comment by fsteggink** [comment]
Op dit moment ben ik hier naar aan het kijken. De SQL-aanpassing is niet zo moeilijk (mits ik het correct interpreteer), maar de Python-aanpassingen wel. Het probleem zit hem in BAGrelatieAttribuut (in bagattribuut.py). In de methods maakInsertSQL, maakCopySQL en maakUpdateSQL wordt de SQL samengesteld om de relatie-records toe te voegen danwel bij te werken. Vanwege de nieuwe kolommen, moeten ook de kolommen verblijfsobjectdstatus en geom_valid worden toegevoegd. In theorie zou ik dan een subklasse moeten maken van de klasse BAGrelatieAttribuut.

Dat roept bij mij de vraag op waarom al deze informatie (identificatie, aanduidingRecordInactief, aanduidingRecordCorrectie, begindatumTijdvakGeldigheid en einddatumTijdvakGeldigheid) gedenormaliseerd opgeslagen moet worden. Kunnen we de drie *actueel en (nieuwe) *actueelbestaand views voor de relatie-objecten niet beter maken o.b.v. joins met verblijfsobject? In de betreffende tabellen hoeft alleen het verblijfsobject-ID en het multiattribuut worden opgeslagen. Er hoeft dan geen subklasse van BAGrelatieAttribuut te worden gemaakt, wat weer in de opslag scheelt. In pull request #148 gebruikt Edward ook een join naar verblijfsobject.

Ik ga even verder met ontwikkelen. Voor dit werk heb ik een aparte branch aangemaakt en als ik dit gereed heb, zal ik een pull request indienen, zodat de code eerst behoorlijk kan worden gereviewed en getest.

**Comment by fsteggink** [comment]
Ik ben wat wijzer geworden. De informatie in de relatietabellen is allemaal nodig, om ervoor te zorgen dat de relatierecords uniek geïdentificeerd kunnen worden.
Een eventuele join met verblijfsobject moet dan ook op basis van al deze kolommen plaatsvinden. Ik heb dit toegepast in de BAG-dump van juni, maar de performance heeft er helaas wel onder te lijden. Een oplossing hiervoor zou het gebruik van materialized views kunnen zijn.

**Comment by justb4** [comment]
Ja precies dat was de reden voor extra attr in tussentabellen: *de relatierecords uniek geïdentificeerd kunnen worden*.

**Comment by fsteggink** [comment]
Ik zit hardop te denken, aangezien ik me nog weinig met BAG-extract heb beziggehouden.
Waarom zitten er indexen (xxx_key) op de kolommen (identificatie, aanduidingrecordinactief, aanduidingrecordcorrectie, begindatumtijdvakgeldigheid, <multiattribuut-veld>), dus incl. het multiattribuut-veld? Ik zou denken dat voor een join met verblijfsobject het betre zou zijn om het multiattribuut-veld buiten de index te houden. Verblijfsobject zelf heeft een eigen index op de bovengenoemde tabellen: verblijfsobject_key.

Verder was ik maandag bezig om aantallen te bekijken o.b.v. een query die is aangepast aan de versie van Daniel, maar mijn machine trok dat niet. Vanochtend geprobeerd om een tabel te maken (ik heb nog Postgres 9.1, dus geen ondersteuning voor materialized views), maar na een uur het statement afgebroken.

Ik ga kijken of het helpt om de indexen aan te passen op de multiattribuut-tabellen, zonder de multiattribuut-velden. Dan kijken of het dan wel haalbaar is om een tabel te maken. Dit doe ik op de originele tabellen, niet de afgeleide views. Hopelijk is dat sneller. Vervolgens ga ik bekijken of het haalbaar is om de query van Daniel te laten kijken naar de actueelbestaand views (in mijn eigen database heb ik die al aangemaakt voor de multiattribuut-tabellen). Anders moet de query van Daniël maar gebruik maken van de onderliggende tabellen en de actuele, bestaande objecten op dezelfde manier uitfilteren zoals nu voor de BAG-tabellen gebeurt. Ik durf niet te zeggen in hoeverre de query optimizer van gaat struikelen over de views.

**Comment by fsteggink** [comment]
Om de relatierecords uniek te identificeren, zou ik een unique index verwachten. Dit geldt ook voor verblijfsobject en de andere BAG-tabellen. Ik weet niet of dit eventueel ten koste gaat van de performance t.o.v. een normale index. Op zich maakt het niet uit of de index uniek is of niet, omdat NLExtract gebruikers de BAG-data niet zelf zullen muteren.

V.w.b. de opname van de multiattribuut-kolom in de indexen op de relatietabellen: dit hangt ervan af welke kolommen er gebruikt wordt. De kolomvolgorde is van invloed. Als je dus alleen gebruik maakt van de eerste x kolommen, dan zou het niet moeten uitmaken. Als je gebruik maakt van willekeurige kolommen, zal het wel uitmaken. Als de eerste kolom niet wordt gebruikt, vindt er een full table scan plaats, tenzij er gebruik gemaakt kan worden van een andere index. Zie [hier](http://use-the-index-luke.com/sql/where-clause/the-equals-operator/concatenated-keys).

**Comment by fsteggink** [comment]
Zojuist heb ik een pull request ingediend. Ik heb de indexen van verblijfsobject en de relatietabellen niet aangepast. In de oplossing heb ik een subklasse van BAGrelatieAttribuut kunnen voorkomen. Dat is maar goed ook, omdat BAGenumRelatieAttribuut hier al een subklasse van is en ik in dat geval hier ook een oplossing voor had moeten verzinnen.

**Comment by justb4** [comment]
Laten we deze dan sluiten. Kan altijd weer geopend als er toch weer een dubbeling optreedt.

**Comment by fsteggink** [comment]
Dubbelingen zullen altijd optreden, zoals Bart aangeeft. Maar door het gebruik van de actueelbestaandviews wordt dit zoveel mogelijk beperkt.
