### ISSUE TITLE
NLExtract BAG CSV dump bevat probleemtekens

### ISSUE THREAD

**Issue by justb4** [opengeogroep/NLExtract#147]
De double quotes (") worden gezet door PostgreSQL wanneer in een kolom het scheidingsteken voorkomt. Dat is op zich correct. Software die de CSV inleest hoort dat te begrijpen (bijv PostgreSQL en GDAL).

Bijvoorbeeld vind ik:

    "Bos, Zee en Duin",82,,,2204BV,Noordwijk,Noordwijk,Zuid-Holland,.....
     Eikenlaan,1,,,5671AA,Nuenen,"Nuenen, Gerwen en Nederwetten",Noord-Brabant,....

Helaas staat er ook soms iets als

     "Hoogerwerfsweg ""De Tong""",1,,,4311NP,Bruinisse,Schouwen-Duiveland,Zeeland,....

Waarschijnlijk zijn hier de quotes weer gequoted.

We kunnen overwegen om een ander scheidingsteken te gebruiken bijv semi-colon/puntcomma. Deze komt (nu) niet in BAG voor. Is ook in lijn met GeoCSV:
http://giswiki.hsr.ch/GeoCSV, dan geeft PostgreSQL:

      Eikenlaan;1;;;5671AA;Nuenen;Nuenen, Gerwen en Nederwetten;Noord-Brabant;....

Het gebruikte commando, zie https://github.com/opengeogroep/NLExtract/blob/master/bag/db/script/adres2csv.sql  nu is is

    \COPY (SELECT openbareruimtenaam as openbareruimte,huisnummer,.. FROM adres ORDER BY .. TO '/tmp/bagadres.csv' WITH CSV HEADER

Dat moet dan worden:

    \COPY (SELECT openbareruimtenaam as openbareruimte,huisnummer,.. FROM adres ORDER BY .. TO '/tmp/bagadres.csv' WITH CSV HEADER DELIMITER ';';

**Comment by gidema** [comment]
We kunnen ook overwegen om \" te gebruiken als escape code voor een dubbele quote, in plaats van "". Daar kunnen de meeste CSV readers (waaronder Excel en Calc) beter mee omgaan. In het Postgresql COPY commando geef je dit aan met `ESCAPE '\'`.
Er is helaas nog geen absolute standaard voor CSV bestanden. Je kunt natuurlijk ook altijd zelf de parameters van het COPY commando aanpassen aan je wensen.

**Comment by justb4** [comment]
Ja denk ik betere oplossing dan ander scheidingsteken. PR welkom.

**Comment by justb4** [comment]
Think it is time for a resolution: will CSV field-separator is now semicolon.
