### ISSUE TITLE
Ondersteuning TOP10NL versie 1.2

### ISSUE THREAD

**Issue by fsteggink** [opengeogroep/NLExtract#153]
De verwachting is dat in november dit jaar het Kadaster gaat beginnen met de uitlevering van TOP10NL volgens versie 1.2. Deze versie bevat diverse veranderingen, waaronder nieuwe featuretypes. Ook vervallen er enkele featuretypes uit versie 1.1.1. Zie de doc-dir bij TOP10extract voor meer informatie.

Het volgende moet gebeuren:
* Nadenken over het ondersteunen van zowel versie 1.1.1 en versie 1.2. Er zal een tijd zijn dat we beide versies moeten ondersteunen, ook al is dit voor een paar maanden.
* Nieuwe versies van diverse configuratiebestanden en scripts:
  * xsl/top10-split_v1.1.1.xsl
  * sql/delete-duplicates.sql
  * sql/drop-tables.sql
  * top10-v1.1.1.gfs
  * etl-top10nl.cfg

De afgelopen dagen ben ik hiermee bezig geweest. Ik heb een voorzetje gemaakt. Hiervoor heb ik een branch top10_v1_2 gemaakt (momenteel nog niet gecommit). Van de hierboven genoemde bestanden heb ik nieuwe versies gemaakt. Ik heb ook een nieuwe versie gemaakt van etl-top10nl.sh. Op deze manier is het mogelijk om beide TOP10NL-versies te ondersteunen, zonder dat ze last van elkaar hebben.

Alle betrokken bestanden hebben een versienummer in de naam gekregen. Dit is of v1.1.1 of v1.2. Dit geldt ook voor de 1.1.1-versies die verder geen wijziging behoeven, om het onderscheid duidelijk te maken. Verder heb ik de GFS-bestanden verhuisd naar een nieuwe gfs-subdirectory en de CFG-bestanden naar een nieuwe conf-subdirectory.

Het GFS-bestand, dat al enorm was, is nog iets gegroeid. Omdat het bijwerken vreselijk veel werk is en de kans op fouten groot, heb ik voor een andere aanpak gekozen. Ik heb een GFS-templatebestand gemaakt (in nieuwe subdir meta), dat met een XSL (NLExtract-root/tools/make-gfs) omgezet kan worden naar een GFS-bestand zoals ogr2ogr verwacht.

In de nieuwe aanpak wordt rekening gehouden met overerving. Op deze manier hoeven generieke TOP10NL properties maar één keer gedefinieerd te worden. Dit geldt ook voor alle properties van de featureklassen zelf. Ik heb niks gewijzigd aan het concept van het uitsplitsen van de GML. Het template-bestand is slechts 26kB groot, terwijl het definitieve GFS-bestand 135kB is.

Het is weliswaar mogelijk om met ogr2ogr tabellen te genereren met meerdere geometriekolommen, maar dat vond ik nog een stap te ver. We zouden hiermee kunnen experimenteren op een nieuwe branch. Voor de ondersteuning van een nieuwe TOP10NL versie is dit out of scope.

Ik wil voorstellen om de veranderingen alleen in de ETL-directory, dus voor de Stetl-versie, uit te voeren. Het ondersteunen van de bin-directory zorgt alleen maar voor nodeloos extra werk. Een voorwaarde vind ik wel dat het laden op Windows moet kunnen gebeuren. Dit doe ik momenteel met MinGW/MSYS. Niet ideaal, maar het werkt wel.

**Comment by justb4** [comment]
Heel mooi initiatief! Paar kleine opmerkingen:

- GFS generatie via XSL: begrijp ik niet goed waarom. Ja de GFS file is groot, maar overzichtelijk en wijzigt eigenlijk nauwelijks. De XSL maakt het proces wat ondoorzichtig m.i. omdat het resultaat GFS weer in GH zit, en mensen dat kunnen gaan wijzigen.

- 1.1.1 vs 1.2. Denk/hoop dat we in half jaar 1.1.1 niet nodig meer hebben, behalve in historische gevallen. Ik zou de naam van het script `etl-top10nl.sh` zo laten en iets van een vlag -v of configuratie-optie bieden. 

Maar goed ik laat het ook aan je eigen inzichten over. We moeten ook iets aan de documentatie doen en mogelijk toch de /bin -versie uitfaseren. Ik ga dan kijken naar de `Stetl .ini` optie ipv `options.sh`: https://github.com/justb4/stetl/issues/22.

**Comment by fsteggink** [comment]
V.w.b. GFS generatie: ik vind hem zelf onhandelbaar groot. De GFS voor 1.2 is 135 kB, terwijl het template-bestand dat als basis is gebruikt 26 kB is. Ik heb ook de GFS voor 1.0/1.1.1 gemaakt, wat niet in een keer goed ging. Dat kwam mede door de omang (119 kB).

V.w.b. script-naam: ik ga hierover nadenken, maar ik denk dat ik het wel eens met je ben ;) Het Kadaster heeft gisteren ook aangegeven in één keer naar 1.2 over te willen gaan. Zie BRT TOP10NL 1.2 demo GML toelichting.pdf in de documentatie.

**Comment by fsteggink** [comment]
Ik heb op een aantal plekken de namespaces bijgewerkt (split XSLT, GML generatie template en demo GML bestand).
De XSD heeft een relevante wijziging, nl. het datatype van Hoogte.hoogte is gewijzigd van integer naar double. Het was me niet eens opgevallen dat het eerst integer was, dus in de code (GFS en GML generatie template + demobestand) heb ik hiervoor niets hoeven aan te passen.

**Comment by fsteggink** [comment]
Een maand geleden heeft het Kadaster TOP10NL in het nieuwe schema beschikbaar gesteld. De import ging zonder problemen. Wel heeft Jan-Willem van Aalst een issue opgemerkt bij attributen met meerdere waarden (als stringlist ingelezen), maar dat is waarschijnlijk een data issue.

Ik heb zojuist de 1.2-branch gemerged in de master en de oude bin-directory verwijderd. De ETL-directory bevat nog wel diverse 1.1.1-configuraties. Die blijven vooralsnog beschikbaar, mocht iemand toch om de een of andere reden oude data willen inlezen.
