### ISSUE TITLE
Documentatie BGT/IMGeo-extract schrijven

### ISSUE THREAD

**Issue by fsteggink** [opengeogroep/NLExtract#161]
TODO

**Comment by justb4** [comment]
Prima! Ik kijk nog naar de commits. De bron doc staat hier: https://github.com/opengeogroep/NLExtract/blob/master/doc/source/top10extract.rst. Bij commit/push wordt ie automagisch gepubliceerd naar http://docs.nlextract.nl/en/latest/, maar wist je denk ik al.

**Comment by fsteggink** [comment]
Zie ook de mail die ik net naar jou heb gestuurd. V.w.b. de ontwerpbeslissingen zal ik twee issues openen, zodat anderen ook hierop kunnen reageren.

**Comment by justb4** [comment]
Aha, zie nu dat 't over BGT (ipv Top10NL) gaat, dan snijdt mijn eerdere comment geen hout!

**Comment by justb4** [comment]
Heb je hier wat aan https://github.com/justb4/stetl/tree/master/examples/bgt ? Hebben ook nog @thijsbrentjens en @ rduivenvoorde aan gewerkt. Was van plan die te verhuizen naar NLExtract voorzover nog relevant.

**Comment by fsteggink** [comment]
On 23-12-2015 17:34, Just van den Broecke wrote:
>
> Heb je hier wat aan 
> https://github.com/justb4/stetl/tree/master/examples/bgt ? Hebben ook 
> nog @thijsbrentjens <https://github.com/thijsbrentjens> en @ 
> rduivenvoorde aan gewerkt. Was van plan die te verhuizen naar 
> NLExtract voorzover nog relevant.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/opengeogroep/NLExtract/issues/161#issuecomment-166938026>.
>
Ik heb er wel naar gekeken, maar nog niet toegepast. De XSL zal ik 
waarschijnlijk niet gaan gebruiken. Hiervoor heb ik de TOP10NL-versie 
als basis / inspiratie gebruikt.

**Comment by fsteggink** [comment]
On 23-12-2015 17:29, Just van den Broecke wrote:
>
> Aha, zie nu dat 't over BGT (ipv Top10NL) gaat, dan snijdt mijn 
> eerdere comment geen hout!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/opengeogroep/NLExtract/issues/161#issuecomment-166936950>.
>
Ik dacht dat die bedoeld was voor het issue dat ik m.b.t. TOP10NL 
documentatie had geschreven ;)

**Comment by fsteggink** [comment]
Ik ben hier vanochtend mee bezig geweest. De TOP10NL documentatie heb ik als basis gebruikt. Het deel over de installatie en het gebruik van het Stetl-framework heb ik in een apart document gestopt. De documentatie zou iets uitgebreider mogen, dus ik laat het issue nog even open staan.

**Comment by fsteggink** [comment]
Ik vind het wel goed zo. Zojuist heb ik de documentatie bijgewerkt.
