### ISSUE TITLE
BRK Kadastrale Kaart, o.a. Kadaster Percelen) - ETL

### ISSUE THREAD

**Issue by justb4** [opengeogroep/NLExtract#166]
Alhoewel de Digitale Kadastrale Kaart in jan 2016 Open Data wordt, kan deze in dec 2015 al gedownload worden via NGR en data.overheid:

https://data.overheid.nl/data/dataset?tags=kadastrale+percelen+perceelgrenzen

http://nationaalgeoregister.nl/geonetwork/srv/dut/search#fast=index&from=1&to=50&keyword=kadastrale percelen, perceelgrenzen&relation=within

Het betreft een subset van IMKAD/BRK: Percelen, Gebouwen en Annotaties. De levering is in GML met eigen schema "BRK-DKK", zie http://www1.kadaster.nl/1/schemas/BRK%20-%20kadastrale%20kaart/v20160101/brkkadastralekaart_v1_1_0.xsd

Dit issue betreft het opzetten van een ETL-keten om de BRK-DKK in te lezen in een OGR-data sink zoals PostGIS, zoals eerder BAG, Top10NL en BGT.

**Comment by fsteggink** [comment]
Ik ben hier de laatste weken mee bezig geweest. Zojuist heb ik een laatste commit gedaan. Op dit moment wordt alles ingelezen; niet alleen perceeldata. Ik neem aan dat dat geen probleem is. Kan het issue gesloten worden?

**Comment by justb4** [comment]
IK zou alleen nog wat willen verbeteren aan de options: deze kunnen nu als .properties file worden meegegeven via ``-a`` optie (n.a.v. jouw verzoek) en hoeft niet perse als shell script, i.v.m. portabilty. Zie dit voorbeeld: https://github.com/justb4/stetl/tree/master/examples/basics/6_cmdargs (``etl.args``). Ik gebruik deze methode in alle nieuw ontwikkelde ETL. Ik kan die verbetering wel doen.

**Comment by fsteggink** [comment]
Dit geldt ook voor de BGT en BRK. Ik heb dit issue al een hele tijd gemarkeerd in mijn mailbox, om er naar te kijken... ;)

**Comment by justb4** [comment]
Voor mij is dit de ideale oplossing waarbij ik de "echte" args file op de ETL-server zet (en dus niet in GitHub):

https://github.com/Geonovum/sospilot/blob/master/src/smartem/last.sh
met
https://github.com/Geonovum/sospilot/blob/master/src/smartem/options-sunda.args
als lokale args ("sunda") is mijn machine-naam.
Dan hoeft iemand nooit GitHub-gebonden files te editen (handig bij updates).

**Comment by fsteggink** [comment]
Ik heb nog een reden om hier naar te kijken. Gisteren liep ik op de machine van iemand anders tegen het feit aan dat de eigen opties niet ingelezen konden worden. Het bestand bestond wel en ook de hoofdletters/kleine letters stonden goed.

Het leek net alsof de regel "[ -x "$host_options" ] && . $host_options" in options.sh werd genegeerd. Als workaround heb ik maar de opties in options.sh goedgezet en STETL_HOME en PYTHONPATH in etl-xxx.sh.

Het was een Windows machine. Het issue trad op bij zowel de OSGeo4W- als de MSYS-shell. De machine was behoorlijk vervuild, maar dat zou voor deze regel niet uit moeten maken.

**Comment by justb4** [comment]
(Eindelijk wat tijd gevonden) Ik heb een eerste versie met `-a options.args` files ipv `options.sh` methode. Volgens mij wordt de args-configuratie (Java-properties file format) nu veel simpeler:

- helderder configuratie, ook geen gekke ~ en quotes etc in `options.sh`
- overrule met eigen `options/<host>.args`
- overrule via command line met eigen `options/<host>.args`
- beter voorbereid op `.bat` versie

Bij overrulen moeten voorlopig alle opties in .args file gespecificeerd. Evt zou Stetl meerdere -a files aankunnen in toekomst maar wordt m.i. minder helder.

Zie ook de README. Alles dankzij jouw oorspronkelijke suggestie!

**Comment by fsteggink** [comment]
Volgens mij kunnen we nu dit issue afsluiten, of niet?

**Comment by fsteggink** [comment]
Issue afgesloten, ik verwacht hier geen werk meer.
