### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by fsteggink** [opengeogroep/NLExtract#167]
Het is onderhand tijd voor een nieuwe release van NLExtract. Recent zijn TOP10NL versie 1.2 en de BGT toegevoegd. Beide maken gebruik van het Stetl-framework. Op 1 jan. jl. is ook de BRK open data geworden. Dit zou een mooie gelegenheid zijn voor een 1.2-milestone.

Er zijn reeds een aantal milestones gedefinieerd, nl. 1.1.5 (met veel BAG-issues en een aantal andere) en 1.1.6 (voor issues die lagere prioriteit hebben).

Mijn voorstel is om de 1.1.5-milestone te hernoemen naar 1.2 en de 1.1.6-milestone naar 1.2.x. Verder heeft Just aan een GUI voor Bag-extract gewerkt, wat mooi de basis zou kunnen zijn voor een release 1.2.1.

**Comment by justb4** [comment]
ok, 1.1.5 is nu 1.2.0 (daarna fixes 1.2.1 etc). Zaken in verdere toekomst v1.3.0+
