### ISSUE TITLE
BAG adres tabel: gebruik actueel ipv actueelbestaande VIEWs

### ISSUE THREAD

**Issue by justb4** [opengeogroep/NLExtract#173]
Een meerdere malen gehoord commentaar is dat er adressen ontbreken in de door NLExtract gegenereerde adres-tabel terwijl de adressen/VBOs wel bestaan. Dat kan zijn omdat de plaatselijke BAG achterloopt, maar ook omdat het script https://github.com/opengeogroep/NLExtract/blob/master/bag/db/script/adres-tabel.sql dat de adres tabel genereerd nogal strict is: alleen actueelbestaande objecten worden meegenomen. Zie ook forum discussie draad: https://groups.google.com/forum/#!topic/nlextract/kwyYEbBSYM0

> Bijvoorbeeld alleen de eerste 12 nummers van Kuyperbrink staan in adres-tabel. De nummers 13 t/m 24 staan wel in de BAG, maar het bijbehorende Verblijfsobject heeft de status "Verblijfsobject gevormd". Dat betekent dat deze niet in de verblijfsobjectactueelbestaand VIEW terecht komt waarmee de adres tabel en dus adres-CSV oa uit gegenereerd wordt.
> 
> De statussen van VBO kunnen zijn:
> ENUM ('Verblijfsobject gevormd', 'Niet gerealiseerd verblijfsobject', 'Verblijfsobject in gebruik (niet ingemeten)', 'Verblijfsobject in gebruik', 'Verblijfsobject ingetrokken', 'Verblijfsobject buiten gebruik');
> 
> Kijk bijv naar VBO voor huisnummer 18: "626019900007004". Het kan natuurlijk zo zijn dat het huis/adres bestaat maar dat de BAG achterloopt. Voor de BAG actueel+bestaande objecten bestaat het adres dus niet.
> 

en voorstel

> Met name voor VBO, LIG, STA, PND en nummeraanduiding zouden we voor de adres tabel de  '...actueel' VIEWs ipv '...actueelbestaand' kunnen meenemen. Een adres blijft tenslotte een adres en is ook niet een officieël BAG object maar een extra NLEXtract faciliteit, ...of is dat weer te gretig?

Dit laatste gaan we doen middels dit issue.

**Comment by justb4** [comment]
Voor bijna alle objecten wordt nu "actueel" genomen ipv "actueelbestaand" tbv adres generatie.

Nog net op tijd voor de feb 2016 BAG: zie http://data.nlextract.nl/bag/csv. Vergelijking: 

- nieuw: feb 2016 (actueel) 9080303 adressen 
- oud: jan 2016 (actueelbestaand) 8663820 adressen

Dus 416483 adressen erbij gekomen, waaronder meer volledige Kuyperbrink Voorschoten: 

```
Kuyperbrink;1;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900006990;VBO;f;91469.181;462104.401;4.45907995828021;52.143472047153
Kuyperbrink;2;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900006991;VBO;f;91469.876;462099.186;4.45909108452544;52.1434252598939
Kuyperbrink;3;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900006992;VBO;f;91470.85;462094.389;4.45910620805803;52.1433822612612
Kuyperbrink;4;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900006993;VBO;f;91471.545;462088.336;4.45911749079953;52.1433279429028
Kuyperbrink;5;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900006994;VBO;f;91477.864;462060.851;4.45921492729017;52.1430816617591
Kuyperbrink;6;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900006995;VBO;f;91478.918;462055.06;4.459231404814;52.1430297392344
Kuyperbrink;7;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900006996;VBO;f;91480.531;462049.757;4.45925595648179;52.142982266596
Kuyperbrink;8;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900006997;VBO;f;91481.516;462044.664;4.45927129566613;52.1429366090536
Kuyperbrink;9;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900006998;VBO;f;91482.779;462039.431;4.45929072171424;52.142889725276
Kuyperbrink;10;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626010000012960;VBO;f;91475.972;461980.624;4.45920227640586;52.1423604451503
Kuyperbrink;11;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626010000012959;VBO;f;91502.837;462004.104;4.45959030500147;52.1425745464308
Kuyperbrink;12;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626010000012958;VBO;f;91531.306;461990.439;4.46000869917958;52.1424550088387
Kuyperbrink;13;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900006999;VBO;f;91518.71;462038.786;4.45981568643634;52.1428880564121
Kuyperbrink;14;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900007000;VBO;f;91518.565;462044.025;4.45981259046886;52.1429351226002
Kuyperbrink;15;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900007001;VBO;f;91518.565;462049.474;4.45981157331444;52.1429840927087
Kuyperbrink;16;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900007002;VBO;f;91518.426;462054.435;4.45980861687168;52.1430286612018
Kuyperbrink;17;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900007003;VBO;f;91518.216;462059.186;4.45980466252179;52.1430713342724
Kuyperbrink;18;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900007004;VBO;f;91518.222;462064.495;4.459803759131;52.1431190468902
Kuyperbrink;19;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900007005;VBO;f;91514.052;462077.889;4.45974034716598;52.1432389396922
Kuyperbrink;20;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900007006;VBO;f;91513.224;462083.715;4.45972716483379;52.1432912027902
Kuyperbrink;21;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900007007;VBO;f;91509.595;462097.1;4.45967165657838;52.1434110768061
Kuyperbrink;22;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900007008;VBO;f;91509.322;462101.629;4.45966682325587;52.1434517475209
Kuyperbrink;23;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900007009;VBO;f;91507.592;462106.964;4.45964055674559;52.1434994943854
Kuyperbrink;24;;;2253VX;Voorschoten;Voorschoten;Zuid-Holland;626019900007010;VBO;f;91505.557;462112.64;4.45960977130783;52.1435502707704
```

**Comment by jochemvankessel** [comment]
Mijn inziens is het voldoende om alleen de verblijfsobjectactueelbestaand aan te passen.
als je daar alleen de filter 'Verblijfsobject gevormt' uit haalt ben je er volgens mij ook.
Je houd dan 8829249 adressen over (waaronder ook de Kuyperbrink Voorschoten). 

Nu krijg je in sommige gevallen -onnodig- dubbele adressen terug uit de adres-tabel waarin oude gegevens staan. 

-- Ben ik nog op tijd voor de mrt 2016 BAG ;-)

**Comment by justb4** [comment]
Hmm dat klinkt niet goed, dubbele adressen kan natuurlijk niet. Heb je daar voorbeelden van?

**Comment by jochemvankessel** [comment]
select * from bagactueel.adres where postcode = '1422CB' and huisnummer = 29 and huisletter is null;

**Comment by jochemvankessel** [comment]
Het kan natuurlijk voorkomen dat een nummeraanduiding meerder adresseerbare objecten heeft, zie bijv. De Kuilart 1, 8723 CG Koudum.

Een object met status 'niet gerealiseerd' of 'ingetrokken' zijn definitief ingetrokken verblijfsobjecten en kunnen dus worden uitgefilterd. In het geval van 1422CB29 is er een nieuw hoofdgebouw (4971m2) gebouwd en is het oude gebouw herverdeeld in eigen adresseerbare objecten (de 29 K ... objecten). Wel zo netjes dat het oude gebouw/indeling (+/-8000m2) dan niet terugkomt in de adrestabel, want die is dan dubbel. 
Volg je me nog? ;-)

**Comment by justb4** [comment]
Ik probeer idd e.e.a. te begrijpen :-). Bijv als ik uit CSV PC `1422CB` met huisnummer `29` zonder huisletter filter, krijg ik 2 adressen, allebij in Uithoorn Wiegerbruinlaan 29. Maar wel met verschillende geometrie, via `grep` :

     grep 'Wiegerbruinlaan;29;;' bagadres.csv 
    Wiegerbruinlaan;29;;;1422CB;Uithoorn;Uithoorn;Noord-Holland;451010000008623;VBO;f;116820.072;473156.767;4.82816539195759;52.2451378233959
    Wiegerbruinlaan;29;;;1422CB;Uithoorn;Uithoorn;Noord-Holland;451010000015187;VBO;f;116814.224;473144.34;4.82808117084038;52.245025731388

Dan zou ik zeggen: dat zijn 2 adrespunten, die eigenlijk een huisletter en/of huisnummertoevoeging moeten krijgen. Als de coordinaten ook identiek waren zou het idd dubbel zijn. Maar zie ook dat VBO `451010000008623` de status `Verblijfsobject ingetrokken` heeft, aha...

Wat je dus zegt voor VBO is dat de conditie voor `verblijfsobjectactueelbestaand` VIEW moet worden aangepast, in `bag-view-actueel-bestaand.sql` , die is nu:

    DROP VIEW IF EXISTS verblijfsobjectactueelbestaand;
    CREATE VIEW verblijfsobjectactueelbestaand AS
        SELECT verblijfsobject.gid,
                verblijfsobject.identificatie,
                verblijfsobject.aanduidingrecordinactief,
                verblijfsobject.aanduidingrecordcorrectie,
                verblijfsobject.officieel,
                verblijfsobject.inonderzoek,
                verblijfsobject.documentnummer,
                verblijfsobject.documentdatum,
                verblijfsobject.hoofdadres,
                verblijfsobject.verblijfsobjectstatus,
                verblijfsobject.oppervlakteverblijfsobject,
                verblijfsobject.begindatumtijdvakgeldigheid,
                verblijfsobject.einddatumtijdvakgeldigheid,
                verblijfsobject.geopunt,
                verblijfsobject.geovlak
        FROM verblijfsobject
        WHERE
          verblijfsobject.begindatumtijdvakgeldigheid <= LOCALTIMESTAMP
          AND (verblijfsobject.einddatumtijdvakgeldigheid is NULL OR verblijfsobject.einddatumtijdvakgeldigheid >= LOCALTIMESTAMP)
          AND verblijfsobject.aanduidingrecordinactief = FALSE
          AND (verblijfsobject.geom_valid is NULL OR verblijfsobject.geom_valid = TRUE)
          AND (verblijfsobject.verblijfsobjectstatus <> 'Niet gerealiseerd verblijfsobject'
          AND verblijfsobject.verblijfsobjectstatus  <> 'Verblijfsobject ingetrokken' 
            AND verblijfsobject.verblijfsobjectstatus  <> 'Verblijfsobject gevormd');

De laatste `verblijfsobjectstatus` filter zou dan worden:

              .
              .
          AND (verblijfsobject.geom_valid is NULL OR verblijfsobject.geom_valid = TRUE)
          AND (verblijfsobject.verblijfsobjectstatus <> 'Niet gerealiseerd verblijfsobject'
          AND verblijfsobject.verblijfsobjectstatus  <> 'Verblijfsobject ingetrokken');

Dan zouden we voor de adres tabel weer `verblijfsobjectactueelbestaand` kunnen gebruiken.

**Comment by justb4** [comment]
Ok, adres-generatie terugezet naar actueelbestaand VIEWs, maar `Verblijfsobject gevormd` status niet mee in actueelbestaand VIEW.

**Comment by jochemvankessel** [comment]
Helemaal super! Dat is inderdaad precies zoals ik het bedoelde.
Ben benieuwd naar de maart editie :+1:

**Comment by justb4** [comment]
De maart BAG editie staat gereed! CSV bevat 8833945 adressen. `Wiegerbruinlaan;29;;;1422CB;Uithoorn` staat er 1x in en `Kuyperbrink 1 t/m 24`.
