### ISSUE TITLE
NLExtract kan niet overweg met GDAL versie 2.0.

### ISSUE THREAD

**Issue by fsteggink** [opengeogroep/NLExtract#175]
Gerapporteerd door Tom Vanzieleghem:

>> >     ik heb een poging ondernomen om de BGT extract te draaien onder
>> >     windows en loop tegen problemen aan met het GFS bestand.
>> >     Uiteindelijk er achter gekomen dat, indien het GFS bestand
>> >     meerdere GMLFeatureClass elementen definieert, ogr2ogr alleen die
>> >     elementen importeert waarvan de naam ongewijzigd blijft (waarde
>> >     van de elementen <Name> en <ElementPath> identiek in het GSF
>> >     bestand). Dit is ook zo als ik rechtstreeks met ogr2ogr werk.
>> >     Enig idee waaraan dit te wijten is?
>> >
>> >     Stetl versie: 1.0.9rc2
>> >     nl-extract bgt versie gedownload begin maart

Later:
>> > Nog wat verder gezocht en het probleem gevonden:
>> >
>> >  1. GDAL versie update van v1.10.0 naar v2.0.2;
>> >  2. Nu kreeg ik bij import wel foutmeldingen waar ik dezeonder de oude
>> >     gdal versie niet kreeg: alleen de import van de eerste feature
>> >     class lukte omdat deze nog alle tabellen moet aanmaken. Import met
>> >     ogr -append optie van daaropvolgende feature classes mislukte met
>> >     een ogr2ogr foutmelding "...current transaction is aborted...".
>> >     Dit blijkt een bug te zijn in ogr die verondersteld opgelost te
>> >     zijn (zie: https://trac.osgeo.org/gdal/ticket/6018). Oplossing is
>> >     om de PG_USE_COPY configuratie op NO te zetten in de stetl
>> >     configuratie. Heeft wel gevolgen voor de performance...

GDAL versie 1.11 blijkt wel te werken. Dit is ook de versie waar ik zelf op ontwikkeld heb.

Waarschijnlijk gaat dit issue niet alleen op voor de BGT, maar ook voor TOP10NL en de BRK.

**Comment by fsteggink** [comment]
Zojuist gefixed in commit 645fee81. Ik merk geen performanceverschil met GDAL 1.11.
Met mijn BGT-testbestand duurde het met --config PG_USE_COPY YES 20 minuten 50 seconden en met --config PG_USE_COPY NO duurde het 20 minuten 41 seconden. 

Met GDAL 2.0 duurde het laden van hetzelfde bestand 21 minuten 12 seconden. Dit kleine performanceverschil merkte ik ook met een ander, kleiner, testbestand.

Tevens heb ik de opties PG_USE_COPY op NO gezet in de configs van TOP10NL en de BRK.

**Comment by justb4** [comment]
Ok, prima zo. `PG_USE_COPY` heeft, als ik mij herinner, te maken of GDAL intern een SQL `COPY` of `INSERT` gebruikt naar PostGIS. In NLExtract-BAG via expliciete PG-calls via `psycopg2` maakte dat wel een enorm verschil, maar misschien doet GDAL intern iets slims met een bulk INSERT oid.
