### ISSUE TITLE
Foutmelding bij laden TOP10NL met GDAL 2.0

### ISSUE THREAD

**Issue by fsteggink** [opengeogroep/NLExtract#178]
BIj het laden van TOP10NL treedt de volgende fout op met GDAL 2.0:

2016-03-23 21:18:14,023 packetwriter INFO writing to file temp/top10-tmp.gml
2016-03-23 21:18:14,729 packetwriter INFO written to temp/top10-tmp.gml
2016-03-23 21:18:14,798 execoutput INFO executing cmd=ogr2ogr -f PostgreSQL "PG:dbname=brt host=localhost port=5432 user=top10nl password=top10nl active_schema=brt" -append -gt 65536 -fieldTypeToString StringList --config PG_USE_COPY NO -lco LAUNDER=YES -
lco PRECISION=NO temp/top10-tmp.gml
ERROR 1: ERROR:  null value in column "gml_id" violates not-null constraint

ERROR 1: INSERT command for new feature failed.
ERROR:  null value in column "gml_id" violates not-null constraint

Command: INSERT INTO "functioneelgebied_punt" ("wkb_geometry" , "fid", "namespace", "lokaalid", "brontype", "bronactualiteit", "bronbeschrijving", "bronnauwkeurigheid", "objectbegintijd", "tijdstipregistratie", "tdncode", "visualisatiecode", "typefunction
eelgebied", "naamnl") VALUES ('010100002040710000C1CAA1452696FD404260E590AF8E2141'::GEOMETRY, 100008251, 'NL.TOP10NL', '100008251', 'TOP10vector', '2004-01-01', 'Digitaal bestand met gecodeerde vectoren. Deze geven tezamen de topografie van Nederland weer
 op de schaal 1:10.000. Voorloper van TOP10NL.', 2000, '2008-11-24', '2008-11-24', 999, 19320, 'natuurgebied, natuurreservaat', '(1:Zeehondenreservaat Eierlandse Gat)') RETURNING "ogc_fid"
ERROR 1: Unable to write feature 0 from layer FunctioneelGebied_Punt.

ERROR 1: Terminating translation prematurely after failed
translation of layer FunctioneelGebied_Punt (use -skipfailures to skip errors)

Deze fout treedt niet op met GDAL 1.11.

**Comment by vanzieto** [comment]
Hoi Frank,

verder gekeken naar deze foutmelding. Is naar ik vermoed te wijten aan een gewijzigde functionaliteit van de OGR GML driver met de fid en gml_id velden sinds versie 1.8.0 (zie http://www.gdal.org/drv_gml.html onder de sectie Feature id).
Ik kreeg de stel conversie werkende onder gdal 2.0 door de config optie --config GML_EXPOSE_GML_ID NO toe te voegen aan de ogr2ogr command line.
Gevolg is wel dat het gml_id veld niet meer wordt aangemaakt maar dat was onder gdal 1.11 ook al niet gevuld. Bovendien is het een samenvoeging van de namespace en de lokaalid welke beide wel worden geïmporteerd.
Om diezelfde reden heb ik ook de import van de fid eruit gehaald in het gfs bestand (was gewoon een kopie van de lokaalid).

beste groet,

Tom

**Comment by fsteggink** [comment]
De fid-kolom heb ik zojuist verwijderd, zie issue #168

**Comment by fsteggink** [comment]
Alhoewel het gml:id redundante informatie bevat, vond ik het een nettere oplossing om het gml:id attribuut te kopiëren naar het tijdelijke GML-bestand. Nu werkt GDAL 2.0 naar behoren. Ik heb ook de BGT en de BRK gecheckt. Hier werken zowel GDAL 1.11 als 2.0.
