### ISSUE TITLE
Vermeld in logging dat het eigen options-bestand niet gevonden kan worden

### ISSUE THREAD

**Issue by fsteggink** [opengeogroep/NLExtract#179]
Het eigen options-bestand kan niet gevonden worden wanneer er bijv. een typefout gemaakt is. Vermeld in de logging (outputten door options.sh) wanneer het bestand $host_options niet aangetroffen is. Dit kan een bewuste keuze zijn, maar vaak is dat niet zo. Het verdient in ieder geval zeer de aanbeveling om een eigen options-bestand te gebruiken.

**Comment by justb4** [comment]
Het gebruik van `$host_options` is bedoeld om lokaal specifieke/eigen (database) settings te specificeren, gebaseerd op host-naam. Vooral bij test/deploy is dat handig omdat dan niet steeds per-machine opties gezet hoeven te worden en productie-passwords niet in GH ingechecked hoeven te worden. Je kunt ook dan een GitHub versie van NLExtract gebruiken en die steeds uptodate houden zonder dat je opties overschreven worden. Het is echter niet altijd even transparant, zeker als het misgaat, plus het is niet cross-platform.

Daarom is er al een tijd de mogelijkheid (in Stetl) om ".args files" (soort .ini files in .properties key=value format) als argument (-a optie) aan stetl te geven. Zie voorbeeld:
https://github.com/justb4/stetl/tree/master/examples/basics/6_cmdargs
Dit is ook cross-platform. Ik stel voor om daarnaar over te stappen. Dan is een .bat ook gemakkelijker te realiseren. Host-specifieke .args files kan nog steeds als deze in etl-top10nl.sh (en .bat) worden gezocht, uiteraard met duidelijke logging!

Ik wil wel een eerste aanzet doen, ik kan issue aanmaken met bovenstaande tekst.

**Comment by fsteggink** [comment]
Ondertussen zijn ook BGT- en Top10-extract geport naar het gebruik van args-file. In de logging is te zien welk options-bestand gebruikt wordt (default.args of <hostname>.args), dus wat mij betreft is dit voldoende.
