### ISSUE TITLE
Maandelijkse PostGIS en CSV dump van BAG is stuk

### ISSUE THREAD

**Issue by justb4** [opengeogroep/NLExtract#180]
Meerdere meldingen, oa..

```Het lijkt er op dat er iets mis gaat met het creeren van de Postgis
dumps van de BAG. De bestanden van april en mei zijn 0 bytes/leeg. Ik ga
inmiddels zelf even een database vullen, maar dacht het even te laten weten.```

Eerste analyse (Just): Er is sprake van een vreemde database corruptie: inlezen BAG in PostGIS gaat goed, maar bij dumpen (pg_dump) komt melding: 

``` pg_dump: schema with OID 694419422 does not exist```

Oplossen blijkt niet zo eenvoudig, zal even (vrije) tijd kosten. Zie bijv http://forums.enterprisedb.com/posts/list/2262.page . Suggesties/hulp welkom.

**Comment by justb4** [comment]
Opgelost: nieuwe DB aangemaakt. Download via http://data.nlextract.nl/bag is weer beschikbaar.

**Comment by bbrala** [comment]
Dank je wel Just :+1: 

Uiteindelijk een probleem gevonden, of is het onverklaarbaar?

**Comment by justb4** [comment]
Het probleem zat in een DB corruptie. Kan op velerlei manieren ontstaan 
zijn, bijv niet regelmatig een VACUUM ANALYZE uitgevoerd. Reden was denk 
niet in NLExtract code/logica zelf :-). Nooit eerder gezien in 10 jaar 
Postgresql.

**Comment by bbrala** [comment]
Gelukkig geen bug dan, wel verwondelijk dat hij zomaar stuk gaat :)
