### ISSUE TITLE
Attribuut bebouwdeKom in TOP10NL(v1.2) plaatsen verkeerd gevuld

### ISSUE THREAD

**Issue by vanzieto** [opengeogroep/NLExtract#182]
In de 1.2 versie van TOP10NL is het attribuut bebouwdeKom foutief gelinkt aan het attribuut naamNL in het GFS bestand. Bijkomend gevolg is dat naamNL leeg blijft.

**Comment by fsteggink** [comment]
Bedankt voor het melden. DIt is zojuist gefixed in commit a552033.

Frank
