### ISSUE TITLE
TOP10NL Plaatsen attribuut aantalinwoners niet gevuld

### ISSUE THREAD

**Issue by vanzieto** [opengeogroep/NLExtract#183]
In versie 1.2 van de TOP10NL conversie blijft het attribuut **aantalinwoners** van de **plaats** elementen leeg a.g.v. een fout in het GFS bestand. De tag **<elementname>** moet **aantalinwoners** zijn i.p.v. **aantalInwoners** (case sensitive).

**Comment by fsteggink** [comment]
On 30-5-2016 11:26, vanzieto wrote:
>
> In versie 1.2 van de TOP10NL conversie blijft het attribuut 
> *aantalinwoners* van de *plaats* elementen leeg a.g.v. een fout in het 
> GFS bestand. De tag ** moet *aantalinwoners* zijn i.p.v. 
> *aantalInwoners* (case sensitive).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/opengeogroep/NLExtract/issues/183>, or mute the 
> thread 
> <https://github.com/notifications/unsubscribe/ABTuBxgrO8wCGM7HTFuhiYGOyfFuTBWCks5qGq1igaJpZM4Ipomo>.
>
Bedankt voor het melden. Ik heb het gefixed. Er bleek ook een fout in 
het GFS-bestand te zitten bij het attribuut Plaats.bebouwdeKom. Hierdoor 
werd zowel dit attribuut als het attribuut naamNL (wat als ElementPath 
voor bebouwdeKom werd gebruikt) niet gevuld.


Frank
