### ISSUE TITLE
Schema wordt niet gerespecteerd bij INSERT en UPDATE

### ISSUE THREAD

**Issue by milovanderlinden** [opengeogroep/NLExtract#34]
Zowel in bagobject.py als in bestuurlijkobject.py wordt bij de inserts en updates geen rekening gehouden met de database schema naam. Dat moet gecorrigeerd worden. Het is in mijn idee niet voldoende om het custom schema als eerste in "SET search_path TO %s,public"  te gebruiken omdat dit database afhankelijk is.

**Comment by justb4** [comment]
Deze discussie lijkt mij gesloten. Ultieme oplossing zou evt BAG via Stetl, dan zijn we geheel onafhankelijk van databases of andere output :-).
