### ISSUE TITLE
BAG : mutaties worden niet correct verwerkt

### ISSUE THREAD

**Issue by justb4** [opengeogroep/NLExtract#55]
Verwerking van BAG mutatie bestanden lijkt niet correct te verlopen. Huidige implementatie is eerste aanzet. Dit issue is bedoeld om:

a) helder krijgen welke acties gedaan moeten worden voor elke mutatie
b) implementeren/testen

ad a)  Met name het goed interpreteren van de acties die gedaan moeten worden op reeds bestaande objecten:

- aanpassen (einddatum bestaand object zetten? en nieuw object aanmaken) 
- wat te doen met alle relaties van een gemuteerd object (worden nu allen vervangen meen ik, maar lijkt mij niet correct, BAG moet steeds hele historie bevatten)

**Comment by justb4** [comment]
Weer een volgende stap: het blijkt wel degelijk nodig om de `<Mutatie-product>` objecten te sorteren op `Tijdstip` en `Volgnummer` verwerking. Een `grep` op een willekeurig mutatie-bestand laat dit zien:

        grep '<product_LVC:TijdstipVerwerking>' mutatie/9999MUT14122014-15122014-000001.xml 
                    <product_LVC:TijdstipVerwerking>2014-12-14T15:00:48.070346</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T15:00:48.070346</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T15:00:49.188262</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T15:00:49.188262</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T16:30:46.023976</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T16:30:46.023976</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T17:00:47.771547</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T17:00:47.771547</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T17:00:47.849754</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T17:00:47.849754</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T15:00:48.154131</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T15:00:48.154131</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T15:00:48.855048</product_LVC:TijdstipVerwerking>
                    <product_LVC:TijdstipVerwerking>2014-12-14T15:00:48.855048</product_LVC:TijdstipVerwerking>

In processor.py zal ik de self.bagObjecten array voor mutaties gesorteerd op  `TijdstipVerwerking` + `VolgnrVerwerking` maken. Zo staat dit ook in de "Koppelvlak BAG – Dienst Extract Schema’s" IMBAG versie v20090901 documentatie. Commit komt eraan...

**Comment by justb4** [comment]
Nog een punt: alleen mutaties met een start datum op of na de stand datum BAG moeten verwerkt. Anders negeren. Dit is simpel te checken via de tabel `nlx_bag_info` waar de stand-datum in is opgeslagen (`WHERE sleutel = 'extract_datum'`...).

**Comment by justb4** [comment]
Beide laatste punten opgelost middels bovenstaande commit. Sorteren mbv sorteer-key functie die juiste datum extraheert uit mutatie-filenaam:

        for each in sorted(os.listdir(file_path), key=fname_key):
                 .
met
        
          def fname_key(filenaam):
             if not filenaam.startswith('9999MUT'):
                return filenaam

             start_datum = filenaam[11:15] + filenaam[9:11] + filenaam[7:9]
             eind_datum = filenaam[20:24] + filenaam[18:20] + filenaam[16:18]
             return filenaam[0:7] + start_datum + '-' + eind_datum + filenaam[24:]

**Comment by bartkraan** [comment]
Beste Just,

De beste wensen voor 2015. 
Goed bezig overigens de laatste dagen!

Zo te zien heb jij dagmutatie bestanden tot je beschikking. Ikzelf heb een abonnement op de maandelijkse mutatiebestanden. Dat komt binnen als een zipfile en de bestandjes daarin hebben een volgnummer in de naam. Sorteren werkt dan prima. 
Kennelijk hebben de dagmutaties een  ddmmjjjj datum in de bestandsnaam. NLExtract zou dus rekening moeten houden met beide varianten. 

Wellicht is het door jou ontdekte voorbeeld van een verkeerde sortering binnen een afzonderlijk mutatiebestand ook wel een dingetje van dagmutaties. Binnen maandmutaties ben ik het nog nooit tegengekomen. 
Nu ik er over nadenk: Zou het wellicht om een ander bagobjecttype kunnen gaan? Binnen de maandmutaties is de sortering ook op objecttype, timestamp, volgnummer. 
Omdat het bij maandmutaties om heel veel mutaties gaat is de stroom vervolgens verdeeld in bestanden van 20Mb met een volgnummer. 
De objecttypes worden zo één voor één op volgorde ingelopen, indien dit vermoeden juist is is er geen probleem. 

Er is overigens volgens mij nergens gedefinieerd dat de sortering altijd zo is. Dus binnen NlExtract hierop alsnog sorteren maakt de boel wel robuuster. 

Waar ik me wel zorgen over maak is het geheugenbeslag bij verwerking van een maandmutatieset. Nu gaat verwerking per bestand van 20 Mb. Dat gaat prima. Indien je eerst wilt sorteren moeten ook eerst alle mutatiebestanden ingelezen worden. Lopen we dan niet tegen grenzen aan?

Ik hoop dat je er wat aan hebt en anders ben ik altijd bereid om vragen te beantwoorden. 

Met vriendelijke groet,
Bart Kraan
Kraan Informatica
+31 6 22 46 09 08

Verstuurd vanaf mijn iPhone

**Comment by justb4** [comment]
On 07-01-15 18:08, bartkraan wrote:
> Beste Just,
>
> De beste wensen voor 2015.
Jij ook, bedankt voor je antwoorden.
> Goed bezig overigens de laatste dagen!
Ja we zaten steeds aan het laatste beetje. Moet nu maar eens af, al heb 
ik eigenlijk geen tijd.
>
> Zo te zien heb jij dagmutatie bestanden tot je beschikking. Ikzelf heb
> een abonnement op de maandelijkse mutatiebestanden. Dat komt binnen als
> een zipfile en de bestandjes daarin hebben een volgnummer in de naam.
> Sorteren werkt dan prima.
> Kennelijk hebben de dagmutaties een ddmmjjjj datum in de bestandsnaam.
> NLExtract zou dus rekening moeten houden met beide varianten.
Heb je anders een voorbeeld bestand dan een maandmutatie? In een 
dagmutatie kunnen ook meerdere bestanden zitten, max 21MB met ieder een 
volgnr op de .zip naam bijv 9999MUT02012015-03012015.zip heeft

21M Jan  3 00:07 9999MUT02012015-03012015-000001.xml
21M Jan  3 00:07 9999MUT02012015-03012015-000002.xml
21M Jan  3 00:07 9999MUT02012015-03012015-000003.xml
.
18M Jan  3 00:07 9999MUT02012015-03012015-000006.xml

Sorteren van de namenlijst in de .zip kan idd met standaard string sort. 
Maar goed, ik wilde ook de case ondersteunen waar meerdere dagbestanden 
zijn uitgepakt op filesysteem.
Heeft een maandmutatie niet de vorm bijv: 9999MUT15012015-14022015.zip?
Dan alleen op datum sorteren bij verwerken meerdere maandmutatie-bestanden.

>
> Wellicht is het door jou ontdekte voorbeeld van een verkeerde sortering
> binnen een afzonderlijk mutatiebestand ook wel een dingetje van
> dagmutaties. Binnen maandmutaties ben ik het nog nooit tegengekomen.
> Nu ik er over nadenk: Zou het wellicht om een ander bagobjecttype kunnen
> gaan? Binnen de maandmutaties is de sortering ook op objecttype,
> timestamp, volgnummer.
> Omdat het bij maandmutaties om heel veel mutaties gaat is de stroom
> vervolgens verdeeld in bestanden van 20Mb met een volgnummer.
> De objecttypes worden zo één voor één op volgorde ingelopen, indien dit
> vermoeden juist is is er geen probleem.
Ben nagegaan: idd klopt wat je zegt: binnen een object-type bijv Pand is 
de sortering goed en verwacht ook over deelbestanden heen. Dus sorteren 
binnen bestand was feitelijk overbodig.

>
> Er is overigens volgens mij nergens gedefinieerd dat de sortering altijd
> zo is. Dus binnen NlExtract hierop alsnog sorteren maakt de boel wel
> robuuster.
>
> Waar ik me wel zorgen over maak is het geheugenbeslag bij verwerking van
> een maandmutatieset. Nu gaat verwerking per bestand van 20 Mb. Dat gaat
> prima. Indien je eerst wilt sorteren moeten ook eerst alle
> mutatiebestanden ingelezen worden. Lopen we dan niet tegen grenzen aan?
Op zich niet. Er hoeft altijd maar 1 bestand ingelezen te worden en 
NLExtract pakt de .zips niet daadwerkelijk uit. Er hoeft niet over files 
heen gesorteerd te worden (zie boven). Een XML file is maximaal 21 MB 
(plm 10000 objecten). Dat is ook bij de gewone, niet-mutatie bestanden. 
Alleen is NLExtract wat trager bij de INSERTs voor mutaties omdat dit 
nog niet optimized (COPY in native Stringbuffer) is.

Net alle mutaties op http://mirror.openstreetmap.nl/bag/mutatie in plm 
20 minuten verwerkt op de gehele BAG van december. Is ook bijna een 
maand aan mutaties. Ging prima.

>
> Ik hoop dat je er wat aan hebt en anders ben ik altijd bereid om vragen
> te beantwoorden.
>
> Met vriendelijke groet,
> Bart Kraan
> Kraan Informatica
> +31 6 22 46 09 08
>
> Verstuurd vanaf mijn iPhone
>
>  > Op 7 jan. 2015 om 14:27 heeft Just van den Broecke
> <notifications@github.com> het volgende geschreven:
>  >
>  > Beste @bartkraan : ik hoop dat je nog meeluistert. Volgens mij gaat
> het sorteren van mutatie-bestanden niet goed wanneer deze in
> verschillende maanden vallen. Dat komt omdat de bestandsnamen de datum
> als DDMMJJ bevatten terwijl in bagfilereader.py op regel 48 en 123
> (laatste GH versie), iets als dit wordt gedaan:
>  >
>  > for each in sorted(os.listdir(file_path)):
>  > Bestandsnamen zijn bijv van 30 dec 2014 t/m 2 jan 2015 sorteren dan
> als volgt:
>  >
>  > 9999MUT01012015-02012015.zip
>  > 9999MUT30122014-31122014.zip
>  > 9999MUT31122014-01012015.zip
>  > Zie bijv http://mirror.openstreetmap.nl/bag/mutatie Dat lijkt mij
> niet de bedoeling. Binnen een XML-mutatiebestand wordt gelukkig wel de
> "mutad", zoals dat vroeger heette, volgorde gedaan, bijv:
> 2014-04-01T12:35:11.899013 (sorteren bleek daar toch nodig, zie boven).
> Klopt mijn redenatie?
>  >
>  > —
>  > Reply to this email directly or view it on GitHub.
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengeogroep/NLExtract/issues/55#issuecomment-69054396>.
>


-- 
kind regards / met vriendelijke groet,

--Just

Just van den Broecke  just@justobjects.nl
Just Objects B.V.     tel +31 65 4268627 Skype: justb4
The Netherlands       http://www.justobjects.nl

**Comment by skinkie** [comment]
Ik heb toch een probleem ontdekt. Als je de BAG van maart vandaag importeert, en daarna mutaties gaat uitrollen krijg je onderstaande foutmelding. Ik denk dat de werkelijke publicatiedatum op een andere manier moet worden vastgesteld.

```
[skinkie@PSC002-02 bag]$ sh bin/bag-extract.sh -e /home/skinkie/bag/9999MUT08032015-09032015.zip
running with lxml.etree
INFO: Start 2015-03-17 01:09:18
INFO: process: verwerk /home/skinkie/bag/9999MUT08032015-09032015.zip
INFO: mutatiebestand 9999MUT08032015-09032015.zip is van eerdere datum-range dan BAG ==> overslaan
INFO: End 2015-03-17 01:09:18
[skinkie@PSC002-02 bag]$ sh bin/bag-extract.sh -e /home/skinkie/bag/9999MUT0
9999MUT08032015-09032015.zip  9999MUT09032015-10032015.zip  
[skinkie@PSC002-02 bag]$ sh bin/bag-extract.sh -e /home/skinkie/bag/9999MUT09032015-10032015.zip 
running with lxml.etree
INFO: Start 2015-03-17 01:09:59
INFO: process: verwerk /home/skinkie/bag/9999MUT09032015-10032015.zip
INFO: mutatiebestand 9999MUT09032015-10032015.zip is van eerdere datum-range dan BAG ==> overslaan
INFO: End 2015-03-17 01:09:59
```

**Comment by justb4** [comment]
Vreemd: de "stand-datum" van de BAG staat altijd in het XML Leveringsdocument: Zie ook issue #140 : "Bij het inlezen van de volledige BAG worden verschillende meta-data gegevens uitgelezen, met name uit het bestand ``Leveringsdocument-BAG-Extract.xml``, en geplaatst in de tabel ``nlx_bag_info``. O.a. het veld ``extract_datum`` met de stand-datum van de BAG levering. Bijv met waarde ``20141231`` (YYYYMMDD).  Bij het inlezen van mutatie-bestanden wordt dit veld geraadpleegd om te waarborgen dat alleen mutaties van na de stand-datum worden verwerkt. Daarnaast wordt gechecked of een mutatie-bestand al ingelezen is via de tabel ``nlx-bag-log``. "

Dus wat staat er in jouw db in het veld: ``extract_datum``  in de tabel ``nlx-bag-log``? Als dat voor zeg, 08032015 is, klopt er idd iets niet (of hoort ``9999MUT08032015-09032015.zip`` bij de BAG van feb 2015). 

De betreffende code staat in ``bagfilereader.py``: 

        # Mutatie-bestand overslaan indien datum eerder dan stand-datum BAG
        if filenaam.startswith('9999MUT'):

            # Draai eerste datum veld om naar YYYYMMDD, bijv:
            # 9999MUT14122014-15122014.zip wordt 20141214
            # 9999MUT02012015-03012015-000002.xml wordt 20150102
            mutatie_start_datum = filenaam[11:15] + filenaam[9:11] + filenaam[7:9]
            mutatie_eind_datum = filenaam[20:24] + filenaam[18:20] + filenaam[16:18]

            # stand datum BAG moet voor of op start-datum mutatie bestand liggen EN
            # voor mutatie einddatum
            sql = "SELECT * FROM nlx_bag_info WHERE sleutel = 'extract_datum' AND waarde <= '%s' AND waarde < '%s'" % (mutatie_start_datum, mutatie_eind_datum)
            if self.database.tx_uitvoeren(sql) != 1:
                Log.log.info("mutatiebestand %s is van eerdere datum-range dan BAG ==> overslaan" % filenaam)
                self.database.log_actie('overgeslagen', filenaam, 'mutatie datum-range voor BAG datum', True)
                return

**Comment by skinkie** [comment]
De door jou genoemde "extact datum" kan ik niet vinden.

Ik zie bijvoorbeeld in kolom bestand:

9999LIG08032015-000001.xml
9999NUM08032015-000001.xml

In nlx_bag_info staat:
```
 gid |        tijdstempel        |         sleutel          | 
waarde
-----+---------------------------+--------------------------+----------------------
   1 | 2015-03-16 01:34:07.17616 | schema_versie            | 1.1.0
   2 | 2015-03-16 01:34:07.17616 | software_versie          | 1.1.4
   3 | 2015-03-16 01:34:07.17616 | schema_creatie           | 16-Mar-2015 
01:34:07
   4 | 2015-03-16 12:53:59.18984 | gem_woonplaats_rel_datum | 20150308
```

**Comment by justb4** [comment]
Lees je wel de gehele BAG in? Inclusief leverings-document: ``Leveringsdocument-BAG-Extract.xml``? Daar lijkt het niet op.

Ik laat NLExtract-BAG op de BAG .zip file los, daarin zit dat leverings document (tenminste in de PDOK levering van BAG). In issue #140 was dit ook het geval. Misschien toch een check of dat record bestaat. Je kunt deze natuurlijk handmatig invullen maar is niet handig. Uit de XML bestandsnamen halen kan evt uit bijv. 9999LIG08032015-000001.xml.

Het idee is om een "onbemande" BAG dagelijkse update te kunnen doen op de directory van mutaties zoals op "mirror". Daarom zijn er 2 checks en logging:

- is de mutatie van toepassing op de BAG in database
- is de mutatie reeds verwerkt

Meerdere keren een mutatie inlezen of de verkeerde mutatie datum, zal de DB-data nl corrumperen.

**Comment by skinkie** [comment]
Ik laat het leveringsdocument om zeer wichtige redenen uit de publicatie op de mirror. Ik verwacht dus dat als ik een mutatie wil laden dat dit kan worden toegestaan. Het voorkomen van corrupte data lijkt me natuurlijk een buitengewoon goed idee.

**Comment by justb4** [comment]
Ik ga dit issue sluiten: m.i. werkt de mutatie-verwerking in NLExtract-BAG nu goed. Zie dit als eerste versie. Indien wijzigingen gewenst of bugs gezien, graag nieuw expliciet issue openen.
