### ISSUE TITLE
viewport meenemen in de adres tabel

### ISSUE THREAD

**Issue by skinkie** [opengeogroep/NLExtract#67]
Het lijkt me zeer interessant om viewport (boundingbox om de objecten) toe te voegen aan de adrestabel. Dit zou theoretisch een update operatie kunnen worden (net als wijken/buurten). Hiermee is het mogelijk de kaart direct op het goede zoomlevel te richten bij het vinden. Het vereist natuurlijk dat er een geovlak beschikbaar is op het object, in tegenstelling tot een geopunt.

**Comment by justb4** [comment]
Meer dan twee jaar geen aktiviteit. Ik neem aan dat de issue niet meer actueel is en ga sluiten. Reopen als echt nodig. Ik zou ook liever de adres tabel lean-and-mean "ACN-achtig" houden.
