### ISSUE TITLE
Laden van BAG views duurt lang in QGis

### ISSUE THREAD

**Issue by fsteggink** [opengeogroep/NLExtract#92]
Gemeld door Jan Heckman op de mailinglijst:

Heb een volledige bag met adressen verkegen. Ik verwacht uiteraard niet dat die een flitsende response geven, maar er is iets aan de hand met de weergave in quantum gis van de views (itt tables).
1) het duurt eindeloos voordat bij postgis laag toevoegen de keuze lijst gemaakt is. Dit is omdat de volledige queries doorlopen worden om het (geo) type van de lagen afgeleid van views te bepalen;

ad 1) dit gebeurt iedere keer bij het opvragen van een bag-laag, dus maakt het gebruik in qgis erg moeilijk.

**Comment by justb4** [comment]
Nog even uitstellen en voor 1.1.6 goed naar kijken.

**Comment by fsteggink** [comment]
Zie issue #185 voor wat meer info

**Comment by fsteggink** [comment]
Net op Gitter met Just over gehad: [June 19, 2016 12:58 PM](https://gitter.im/opengeogroep/NLExtract?at=57667af2a82a6b0079a6f84b)
1.5 wordt amper meer gebruikt.
