### ISSUE TITLE
BAG-views kunnen niet in QGis worden getoond

### ISSUE THREAD

**Issue by fsteggink** [opengeogroep/NLExtract#93]
Door Jan Heckman gemeld op de mailinglijst:

Heb een volledige bag met adressen verkegen. Ik verwacht uiteraard niet dat die een flitsende response geven, maar er is iets aan de hand met de weergave in quantum gis van de views (itt tables).
2) daarna kunnen de viewlagen toch niet gebruikt worden in qgis omdat er geen primary key is.

ad 2) wat googlen leverde mij (na een biertje of 2) weinig verteerbare info over primary keys van views in postgresql. Het ligt voor de hand dat dit wat zinloos is, omdat via een primary key een persistente dataset aka table zou ontstaan. Maar er leek toch weer een beetje hoop: http://osgeo-org.1560.n6.nabble.com/postgresql-postgis-views-and-primary-keys-td3796362.html.

(Het 1e deel betreft het traag laden van de lagen in QGis, omdat het geometrietype nog bepaald moet worden.)

**Comment by fsteggink** [comment]
Ik denk dat dit issue gesloten kan worden. Het gegeven antwoord op [StackOverflow](http://gis.stackexchange.com/a/25756) werkt gewoon.
De aanpassing aan de view om het geometrietype te registreren heeft betrekking op issue #92.

**Comment by justb4** [comment]
Ok!
